### ISSUE TITLE
Feature request: Prevent .env.schema throw if set in env

### ISSUE THREAD

**Issue by scottmas** [keithmorris/node-dotenv-extended#17]
Shouldn't the schema validation in .env.schema be run against process.env, not just the values dotenev-extended loads? I'm in a situation where I want to use the behavior of dotenv where it does not override env variables if they are set, but still get schema validation. 

For example, 

```
# .env.schema
SOME_ENV_VAR=
```
```
# .env
# Do nothing
```
```
// server.js
require('dotenv-extended').load({errorOnMissing: true})
```
```bash
SOME_ENV_VAR='env value' node server.js
```

And we would expect running server.js to NOT throw when we set the env var as a true environment variable.

For backwards compatibility we could have a new option: `validateAgainstProcess` or something like that.

**Comment by niftylettuce** [comment]
This is fixed in <https://github.com/keithmorris/node-dotenv-extended/pull/16> (specifically this commit https://github.com/ladjs/dotenv-extended/commit/b3d5052a2236141349da9dfaa67a35ea1032b235).

I've published my version to npm since this package seems to not be maintained.  See the GitHub repo at https://github.com/ladjs/dotenv-extended or download it via `npm install --save @ladjs/dotenv-extended`.

You might also want to take a look at our work with https://github.com/ladjs/env, since it also lets you parse variables using <https://github.com/niftylettuce/dotenv-parse-variables> and use Mustache templating in your dotenv config files.

**Comment by victorandree** [comment]
@niftylettuce I don't think your commit fixes this issue, since it looks at `configData` to determine which variables to override using `process.env`. This means that process.env keys *not* in config data (because they have no defaults) will not become part of it. However, if you provide (empty) values in your defaults, then the validation passes because config data will have the keys.

I would rather expect the validation for missing keys to be once the environment has been loaded (i.e. it validates your environment), whereas the validation for extra keys would happen where it does currently (i.e. it validates your .env files).
