### ISSUE TITLE
question: How to combine with dotenv-expanded

### ISSUE THREAD

**Issue by ikeamanual** [keithmorris/node-dotenv-extended#6]
Hi,

Is there a nice way to combine dotenv-extended with dotenv-expanded?

This does not work:
```
const dotenvExtended = require('dotenv-extended').load({
    silent: false,
    errorOnMissing: true,
    errorOnExtra: true,
})
debug(`dotenvExtended = ${JSON.stringify(dotenvExtended, null, 2)}`)

const dotenvExpand = require('dotenv-expand')
dotenvExpand(dotenvExtended)
debug(`dotenvExtended expanded = ${JSON.stringify(dotenvExtended, null, 2)}`)
```

I know it's not 12factor but it's dryer...

regards,

Peter

**Comment by keithmorris** [comment]
@ikeamanual I did some tests with a modified version of the code you supplied above using both `dotenv` and `dotenv-extended` which yielded the same results. Note, I replaced `debug` with `console.log`.

Assuming the `.env` contains the following (from the `dotenv-expand` repository):
```
NODE_ENV=test
BASIC=basic
BASIC_EXPAND=$BASIC
MACHINE=machine_env
MACHINE_EXPAND=$MACHINE
UNDEFINED_EXPAND=$UNDEFINED_ENV_KEY
ESCAPED_EXPAND=\$ESCAPED
MONGOLAB_DATABASE=heroku_db
MONGOLAB_USER=username
MONGOLAB_PASSWORD=password
MONGOLAB_DOMAIN=abcd1234.mongolab.com
MONGOLAB_PORT=12345
MONGOLAB_URI=mongodb://${MONGOLAB_USER}:${MONGOLAB_PASSWORD}@${MONGOLAB_DOMAIN}:${MONGOLAB_PORT}/${MONGOLAB_DATABASE}
```

I have the following modified code. If you toggle commenting out lines 1 and 2, you will switch between `dotenv` and `dotenv-extended`:

```javascript
const dotenv = require('dotenv-extended').load({
// const dotenv = require('dotenv').load({
    silent: false,
    errorOnMissing: false,
    errorOnExtra: false,
})

console.log(`dotenv = ${JSON.stringify(dotenv, null, 2)}`)

const dotenvExpand = require('dotenv-expand')
dotenvExpand(dotenv)
console.log(`dotenv expanded = ${JSON.stringify(dotenv, null, 2)}`)
```

When I run that code using either `dotenv` or `dotenv-extended` I get the following identical results:
```javascript
dotenv = {
  "NODE_ENV": "test",
  "BASIC": "basic",
  "BASIC_EXPAND": "$BASIC",
  "MACHINE": "machine_env",
  "MACHINE_EXPAND": "$MACHINE",
  "UNDEFINED_EXPAND": "$UNDEFINED_ENV_KEY",
  "ESCAPED_EXPAND": "\\$ESCAPED",
  "MONGOLAB_DATABASE": "heroku_db",
  "MONGOLAB_USER": "username",
  "MONGOLAB_PASSWORD": "password",
  "MONGOLAB_DOMAIN": "abcd1234.mongolab.com",
  "MONGOLAB_PORT": "12345",
  "MONGOLAB_URI": "mongodb://${MONGOLAB_USER}:${MONGOLAB_PASSWORD}@${MONGOLAB_DOMAIN}:${MONGOLAB_PORT}/${MONGOLAB_DATABASE}"
}
dotenv expanded = {
  "NODE_ENV": "test",
  "BASIC": "basic",
  "BASIC_EXPAND": "basic",
  "MACHINE": "machine_env",
  "MACHINE_EXPAND": "machine_env",
  "UNDEFINED_EXPAND": "",
  "ESCAPED_EXPAND": "$ESCAPED",
  "MONGOLAB_DATABASE": "heroku_db",
  "MONGOLAB_USER": "username",
  "MONGOLAB_PASSWORD": "password",
  "MONGOLAB_DOMAIN": "abcd1234.mongolab.com",
  "MONGOLAB_PORT": "12345",
  "MONGOLAB_URI": "mongodb://${MONGOLAB_USER}:${MONGOLAB_PASSWORD}@${MONGOLAB_DOMAIN}:${MONGOLAB_PORT}/${MONGOLAB_DATABASE}"
}
```

Note, the last line is correctly not expanded because `dotenv-expand` does not expand template strings per its test spec:
`mongodb://${MONGOLAB_USER}:${MONGOLAB_PASSWORD}@${MONGOLAB_DOMAIN}:${MONGOLAB_PORT}/${MONGOLAB_DATABASE}`

Can you verify you are seeing the same thing?

**Comment by ikeamanual** [comment]
Hello Keith,

Thanks for taking the time to look into it.
I can confirm that I am seeing the same thing, it all works as specified.

I was using it like this:

PORT=3001
...
APP_URL=http://192.168.1.123:$PORT

Apparently dotenv-expand sees this also as a template string.
If you test with:

BASIC_EXPAND2=whatever$BASIC
BASIC_EXPAND3=whatever $BASIC
BASIC_EXPAND4=$BASIC whatever

It will not expand.

Anyway, the lesson is that it is better to do these kind of concatenations in the code instead of any configuration file.

thanks,

Peter
